In [2]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [11]:
import numpy as np
a=np.array([1,2,3,4],[1,2,3,4]);

TypeError: Field elements must be 2- or 3-tuples, got '1'

In [7]:
a

array([1, 2, 3, 4])

In [5]:
a.ndim


1

In [5]:
a.shape

(4,)

In [6]:
a.itemsize

4

In [7]:
a.dtype

dtype('int32')

In [14]:
a=np.array([[1,2,3],[3,4,5],[6,7,8]],dtype=np.complex)

In [15]:
a

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [3.+0.j, 4.+0.j, 5.+0.j],
       [6.+0.j, 7.+0.j, 8.+0.j]])

In [11]:
a.itemsize


8

In [12]:
a.size

9

In [13]:
a.shape

(3, 3)

In [20]:
import numpy as np
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
i=range(3)

In [22]:
i

range(0, 3)

In [28]:
i[2]

2

In [29]:
np.arange(1,5)

array([1, 2, 3, 4])

In [33]:
a=np.arange(1,55,5)

In [34]:
a

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51])

In [35]:
np.sqrt(a)

array([1.        , 2.44948974, 3.31662479, 4.        , 4.58257569,
       5.09901951, 5.56776436, 6.        , 6.40312424, 6.78232998,
       7.14142843])

In [36]:
pip install pandas


Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
ar=np.array([[2,3,1],[3,5,1],[5,7,3]])

In [3]:
ar

array([[2, 3, 1],
       [3, 5, 1],
       [5, 7, 3]])

In [6]:
[m,n]=ar.shape

In [7]:
n

3

In [8]:
m

3

In [9]:
ar2=np.arange(1,11,.5)

In [10]:
ar2

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5])

In [11]:
ar2=np.arange(1,55,5)

In [12]:
ar2

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51])

In [22]:
ar3=np.arange(1,10,9/500)

In [23]:
ar3

array([ 1.   ,  1.018,  1.036,  1.054,  1.072,  1.09 ,  1.108,  1.126,
        1.144,  1.162,  1.18 ,  1.198,  1.216,  1.234,  1.252,  1.27 ,
        1.288,  1.306,  1.324,  1.342,  1.36 ,  1.378,  1.396,  1.414,
        1.432,  1.45 ,  1.468,  1.486,  1.504,  1.522,  1.54 ,  1.558,
        1.576,  1.594,  1.612,  1.63 ,  1.648,  1.666,  1.684,  1.702,
        1.72 ,  1.738,  1.756,  1.774,  1.792,  1.81 ,  1.828,  1.846,
        1.864,  1.882,  1.9  ,  1.918,  1.936,  1.954,  1.972,  1.99 ,
        2.008,  2.026,  2.044,  2.062,  2.08 ,  2.098,  2.116,  2.134,
        2.152,  2.17 ,  2.188,  2.206,  2.224,  2.242,  2.26 ,  2.278,
        2.296,  2.314,  2.332,  2.35 ,  2.368,  2.386,  2.404,  2.422,
        2.44 ,  2.458,  2.476,  2.494,  2.512,  2.53 ,  2.548,  2.566,
        2.584,  2.602,  2.62 ,  2.638,  2.656,  2.674,  2.692,  2.71 ,
        2.728,  2.746,  2.764,  2.782,  2.8  ,  2.818,  2.836,  2.854,
        2.872,  2.89 ,  2.908,  2.926,  2.944,  2.962,  2.98 ,  2.998,
      

In [24]:
len(ar3)

501

In [25]:
ar4=np.linspace(1,12,500)

In [27]:
print(ar4)

[ 1.          1.02204409  1.04408818  1.06613226  1.08817635  1.11022044
  1.13226453  1.15430862  1.17635271  1.19839679  1.22044088  1.24248497
  1.26452906  1.28657315  1.30861723  1.33066132  1.35270541  1.3747495
  1.39679359  1.41883768  1.44088176  1.46292585  1.48496994  1.50701403
  1.52905812  1.5511022   1.57314629  1.59519038  1.61723447  1.63927856
  1.66132265  1.68336673  1.70541082  1.72745491  1.749499    1.77154309
  1.79358717  1.81563126  1.83767535  1.85971944  1.88176353  1.90380762
  1.9258517   1.94789579  1.96993988  1.99198397  2.01402806  2.03607214
  2.05811623  2.08016032  2.10220441  2.1242485   2.14629259  2.16833667
  2.19038076  2.21242485  2.23446894  2.25651303  2.27855711  2.3006012
  2.32264529  2.34468938  2.36673347  2.38877756  2.41082164  2.43286573
  2.45490982  2.47695391  2.498998    2.52104208  2.54308617  2.56513026
  2.58717435  2.60921844  2.63126253  2.65330661  2.6753507   2.69739479
  2.71943888  2.74148297  2.76352705  2.78557114  2.8

In [46]:
ar3=np.arange(1,2,.565)
print(ar3)
len(ar3)

[1.    1.565]


2

In [42]:
ar3=np.arange(1,10,100/101)
print(ar3)

[1.         1.99009901 2.98019802 3.97029703 4.96039604 5.95049505
 6.94059406 7.93069307 8.92079208 9.91089109]


In [49]:
ar5=np.random.rand(1,5) #random float values will be printed there

In [50]:
ar5

array([[0.46717962, 0.79992933, 0.14850393, 0.25372441, 0.68987011]])

In [55]:
ar5=np.random.rand(2,3)

In [56]:
ar5.shape

(2, 3)

In [5]:
import numpy as np
x=np.random.randn(3,3)

In [6]:
x

array([[[ 0.20448856, -0.48164959],
        [ 1.05820406, -0.07442985],
        [-0.34992039, -0.06446847]],

       [[-0.06791407, -1.56224958],
        [ 0.88186938, -0.28804731],
        [-0.26357037,  0.04259276]],

       [[-0.11030682, -0.49545405],
        [ 1.5739669 ,  0.93218865],
        [-0.03739754, -0.96590738]]])

In [63]:
x.shape

(3, 3)

In [64]:
ar5=np.random.rand(5,6)
#structure (randomly generator fuction (size))

In [68]:
np.random.randint(2,size=(4,3))

ValueError: low >= high

In [5]:
import numpy as np
np.random.randint(1,size=(3,3,3))

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [6]:
import numpy as np
np.random.randint(1,size=(3,3,3))

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [7]:
np.zeros(shape=(3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [8]:
?np.random.rand