In [1]:
import numpy as np

# Numpy Exercise Solution  <img src = "numpy1.png">
###### Authored by Nagendra yadav

#### 1. Create a numpy array with the number of elements equals your age. The value of array elements is a random number between 10 to your age 

In [2]:
myage=np.random.randint(10,21,size=(20))
print(myage)

[14 16 10 20 17 13 12 13 19 16 16 12 15 14 15 19 10 15 18 20]


#### 2. Create a numpy array between 1 to 50 with the span(space) of 2 and print the length of the array

In [3]:
# Solution
arr=np.arange(1,50,2)
print(arr)


[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


#### 3. Create an equally spaced numpy array with 27 elements between 4 and 7 

In [4]:
# Solution
Equallyspaced=np.linspace(4,7,27)
print(Equallyspaced)


[4.         4.11538462 4.23076923 4.34615385 4.46153846 4.57692308
 4.69230769 4.80769231 4.92307692 5.03846154 5.15384615 5.26923077
 5.38461538 5.5        5.61538462 5.73076923 5.84615385 5.96153846
 6.07692308 6.19230769 6.30769231 6.42307692 6.53846154 6.65384615
 6.76923077 6.88461538 7.        ]


#### 4. Create a matrix of size (5 x 4) with random numbers and round off the each elements by only 2 fractional points.

In [10]:
# Solution
randomatrix=np.round(np.random.randn(5,4),2)
print(randomatrix)


[[ 1.58 -2.45 -2.43  1.1 ]
 [-0.67 -0.33 -0.64  0.34]
 [-1.4  -0.62  1.34  0.99]
 [ 0.4  -0.39  1.36  0.23]
 [-0.94 -0.72 -0.07  0.65]]


#### 5. Create a matrix of size (5x5) with random integers between 5 to 15

In [13]:
# Solution
np.random.randint(10,15,size=(5,5))


array([[13, 13, 13, 13, 10],
       [14, 12, 13, 11, 11],
       [10, 12, 10, 14, 10],
       [13, 12, 13, 13, 12],
       [14, 10, 12, 11, 11]])

#### 6. Create the one dimensional array of zeros of random length below 20 with the data type int32

In [16]:
# Solution

np.zeros(np.random.randint(20))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 7. Create a two dimensional array of ones of random row and column lengths with the data type of float32 

In [20]:
# Solution

np.ones((np.random.randint(10),np.random.randint(10)))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

#### 8. Create a matrix exactly as same as shown below and print its shape, type and dtype
<img src = "np_mat1.png">

In [5]:
import numpy as np
x = np.array([ [9, 25, 50, 34, 45],
               [3, 34, 34, 65, 2],
               [5, 7, 3, 76, 3],
               [7, 8, 6, 54, 6],
               [23, 12, 8, 5, 8]])
print(np.shape(x))
print(x.ndim)
print(x.dtype)

x

(5, 5)
2
int32


array([[ 9, 25, 50, 34, 45],
       [ 3, 34, 34, 65,  2],
       [ 5,  7,  3, 76,  3],
       [ 7,  8,  6, 54,  6],
       [23, 12,  8,  5,  8]])

#### 9. Access the center pixel of the matrix defined in the question no 8 ( Don't enter the row and column index explicitely)

In [10]:
# Solution



#### 10. Print the all the elements of 3rd row of the matrix

In [35]:
# Solution
z[:,1]

array([25, 34,  7])

#### 11. Print the all the elements of 4th columns of the matrix

In [12]:
# Solution


#### 12. Print the 4 corner pixels of the matrix

In [15]:
z = np.array([ [9, 25, 50, 34, 45],
               [3, 34, 34, 65, 2],
               [5, 7, 3, 76, 3],
               [7, 8, 6, 54, 6],
               [23, 12, 8, 5, 8]])
print(np.shape(x))
print(z.ndim)
print(z.dtype)

(5, 5)
2
int32


#### 13. Create three matrix m1,m2,m3 with the elements grouped in the figure below
<img src = "np_mat2.png">

In [16]:
# Solution 


#### 14. Reshape all the three matrix segmented in the above task in to three  1-dimensional vector.

#### 15. Concatenate the matrix m1 and m2 in both vertical and horizontal direction

In [17]:
# Solution
m1=z[0:2,2:4]
m3=z[2:5,2:5]
m2=z[3:5,0:2]
print(m1)
print(m2)
print(m3)

[[50 34]
 [34 65]]
[[ 7  8]
 [23 12]]
[[ 3 76  3]
 [ 6 54  6]
 [ 8  5  8]]


#### 16. Add, Subtract, multiply, divide the matrixes m1 and m2

In [19]:
# Solution

a=m1+m2

s=m1-m2

m=m1*m2

d=m1/m2
print("Addition:",a)
print("subtraction:",s)
print("multiplication",m)
print("division",d)


Addition: [[57 42]
 [57 77]]
subtraction: [[43 26]
 [11 53]]
multiplication [[350 272]
 [782 780]]
division [[7.14285714 4.25      ]
 [1.47826087 5.41666667]]


#### 17. Add the m1 with m3 by removing the first row and last column of m3

In [46]:

x=np.delete(m3,(0),axis=0)
y=np.delete(x,(2),axis=1)
m3=np.add(m1,y)
print(y1)



[[56 88]
 [42 70]]


#### 18. Form the matrix m4 by concatenating (as a new row) the vector [me1, me2] with the matrix m1, where me1 and me2 are the mean values of each column on m1.

In [47]:
# Solution
me1=np.mean(m1[:,0])
me2=np.mean(m1[:,1])
m4=np.hstack([me1,me2])
m4


array([42. , 49.5])

#### 19. Perform the matrix multiplication between m3 and m4

In [53]:
# Solution
print("Multiplication:",m3*m4)

mul=np.multiply(m3,m4)
print(mul)

Multiplication: [[2352. 4356.]
 [1764. 3465.]]
[[2352. 4356.]
 [1764. 3465.]]


#### 20. Compute the maximum and minimum value of mean, variance, standard deviation for each row of matrix created in question number 8.

Maximum in matrix 76
Minimum in Matrix: 2
Varience: 456.44159999999994
Mean: 21.28


In [58]:
a=np.array([[9,25,50,34,45],[3,34,34,65,2],[5,7,3,76,3],[7,8,6,54,6],[23,12,8,5,8]])
print(min(np.mean(a,axis=1)))
print(max(np.mean(a,axis=1)))
print(min(np.var(a,axis=1)))
print(max(np.var(a,axis=1)))
print(min(np.std(a,axis=1)))
print(max(np.std(a,axis=1)))

11.2
32.6
39.760000000000005
820.1600000000001
6.305553108173779
28.63843571147


#### 21. Compute the average and strike rate for each player and sort it decending way (seperately for avg and strike rate)
<img src = 'crick1.png'>

In [67]:
# Solution 
runs=np.array([['MSD',54,60,10,65],
               ['Kholi',102,2,78,32],['Rohit',3,110,1,92],
               ['Rahul',56,6,12,42],['Dhawan',12,8,22,11]])

balls=np.array([['MSD',50,42,22,78],['Kholi',95,8,65,43],['Rohit',9,100,7,101],['Rahul',27,3,11,31],['Dhawan',24,20,36,27]])


In [69]:
print(balls)
ball=ball
print(runs)

[['MSD' '50' '42' '22' '78']
 ['Kholi' '95' '8' '65' '43']
 ['Rohit' '9' '100' '7' '101']
 ['Rahul' '27' '3' '11' '31']
 ['Dhawan' '24' '20' '36' '27']]
[['MSD' '54' '60' '10' '65']
 ['Kholi' '102' '2' '78' '32']
 ['Rohit' '3' '110' '1' '92']
 ['Rahul' '56' '6' '12' '42']
 ['Dhawan' '12' '8' '22' '11']]


#### 22. The students mark was recorded in a numpy array: marks = np.array([65,84,47,56,89,98,48,77,80,39]).  Cutoff for pass is 50 marks. Write the logic to print the number of students passed and failed. 

#### 23. The class incharge decided to give a mercy mark of 5 for those who scored between 45 and 49. Also the bonus of 5 marks awarded to the students who scored more than 80. Print all the student marks and compute the increase in the pass percentage of class. Any score more than 100 must be recorded as only 100.

#### 24. Print the time taken for performing the following operation using list and numpy array
####       (x(i)^2 +8) / y(i),   where x and y are real integers from 1 to 60000

#### 25. Create a Github account and upload your solution with the short write-up on Numpy

In [25]:
# Solution

