# Hey
## hello
### bye

c:\users\user\appdata\local\programs\python\python39\lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')


In [2]:
pip install fuzzywuzzy

Note: you may need to restart the kernel to use updated packages.


In [4]:
from fuzzywuzzy import fuzz

In [5]:
import array

In [6]:
ls=list(range(10))

In [7]:
ls

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [24]:
type(ls)

list

In [15]:
var=array.array("i",ls)# i indicate ther integaer here

In [16]:
var

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
print(var)

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [18]:
import numpy as np

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
np.empty(4)

array([2.12199579e-314, 2.16847386e-028, 3.51774740e-321, 3.79442416e-321])

# Data Types of Nupy


-boolen (true or false)
-int "$int32$" and "$int64$",("int8",use in indexing)

-float "float32" and "float64"

-complex complex64 and complext32 comes unse the float

In [25]:
#seed

In [26]:
x1=np.random.seed(1)

In [39]:
var1=np.random.randint(10,size=6)
var2=np.random.randint(10,size=(5,5))
var3=np.random.randint(10,size=(4,5,6))

In [40]:
print("the diminsion",var1.ndim)
print("the shape of value",var2.shape)
print("size is",var3.size)
print("the dtype is ",var3.dtype)

the diminsion 1
the shape of value (5, 5)
size is 120
the dtype is  int32


In [41]:
var2

array([[7, 5, 3, 8, 8],
       [0, 6, 7, 9, 5],
       [4, 9, 5, 2, 5],
       [6, 6, 8, 7, 7],
       [7, 2, 6, 0, 5]])

In [42]:
var2[0][0]

7

In [44]:
var2[0,0] #indexing can be done is same way row,column

7

In [50]:
var2[2,2:4]

array([5, 2])

In [51]:
# from secound row strach 34

In [60]:
var1

array([0, 3, 9, 0, 3, 4])

In [61]:
var1[2:]

array([9, 0, 3, 4])

In [62]:
var1[2:4]

array([9, 0])

In [63]:
var2

array([[7, 5, 3, 8, 8],
       [0, 6, 7, 9, 5],
       [4, 9, 5, 2, 5],
       [6, 6, 8, 7, 7],
       [7, 2, 6, 0, 5]])

In [65]:
var2[::-1,::-1]

array([[5, 0, 6, 2, 7],
       [7, 7, 8, 6, 6],
       [5, 2, 5, 9, 4],
       [5, 9, 7, 6, 0],
       [8, 8, 3, 5, 7]])

In [66]:
var2[::-1]

array([[7, 2, 6, 0, 5],
       [6, 6, 8, 7, 7],
       [4, 9, 5, 2, 5],
       [0, 6, 7, 9, 5],
       [7, 5, 3, 8, 8]])

In [67]:
var2[::-1]

array([[7, 2, 6, 0, 5],
       [6, 6, 8, 7, 7],
       [4, 9, 5, 2, 5],
       [0, 6, 7, 9, 5],
       [7, 5, 3, 8, 8]])

In [90]:
#reshaping the array 
var4=np.arange(1,10).reshape(3,3)

In [91]:
var4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [92]:
var4.reshape(1,10)

ValueError: cannot reshape array of size 9 into shape (1,10)

In [83]:
##reshape
## you hvae called emp table here present only 1 ow and you have 5 column 
##you hvae an another data department table they have 2 rows and 10 columns
var=np.array([1,2,3,4,5,6])

In [84]:
var

array([1, 2, 3, 4, 5, 6])

In [93]:
var.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [94]:
var.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
var.reshape(6,1)

In [95]:
var5=np.arange(1,5)
var6=np.arange(6,10)

In [96]:
print(var5)
print(var6)

[1 2 3 4]
[6 7 8 9]


In [98]:
var7=np.concatenate([var5,var6])

In [99]:
var7

array([1, 2, 3, 4, 6, 7, 8, 9])

In [100]:
var8=np.var8=np.concatenate([var6,var5])

In [101]:
var8

array([6, 7, 8, 9, 1, 2, 3, 4])

In [104]:
var8=var8=np.concatenate([var6,var5,var7,var6])

In [105]:
var8

array([6, 7, 8, 9, 1, 2, 3, 4, 1, 2, 3, 4, 6, 7, 8, 9, 6, 7, 8, 9])

In [106]:
#spit function
#same as the string and we done lit previously 



AttributeError: 'numpy.ndarray' object has no attribute 'split'

In [122]:
var9=np.arange(1,11)

In [123]:
var9

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [124]:
var10=np.split(var9,[2])

In [125]:
var10

[array([1, 2]), array([ 3,  4,  5,  6,  7,  8,  9, 10])]

In [126]:
var11,var12,var13=np.split(var9,[2,5])

In [127]:
print(var11,var12,var13)

[1 2] [3 4 5] [ 6  7  8  9 10]


In [130]:
var11,var12,var13=np.split(var9,[2,5])

In [136]:
var13=np.split(var9,[9])

In [137]:
var13

[array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([10])]

# Arthmatic Fuction in Nupy
- np.add(+)
- np.subract(-)
- np.multiply(*)
- np.division()/
- np.floor(//)
- np.mod(%)
- np.power('')
- np.sqrt('')

In [148]:
a1=np.array([11,99,55,42,-20,6,0,-13])

In [149]:
a1

array([ 11,  99,  55,  42, -20,   6,   0, -13])

In [150]:
a2=np.abs(a1)

In [151]:
a2

array([11, 99, 55, 42, 20,  6,  0, 13])

In [152]:
a4=np.add(a1,a2)

In [153]:
a4

array([ 22, 198, 110,  84,   0,  12,   0,   0])

In [162]:
#a3=np.arange(12,25)
a3=np.arange(6)

In [163]:
print("value is :",a3+55)
print("value is",a3-10)
print("value is",a3*12)
print("value is",a3/6)
print("value is",a3//6)
print("value is",a3**6)
print("value is",a3%6)


value is : [55 56 57 58 59 60]
value is [-10  -9  -8  -7  -6  -5]
value is [ 0 12 24 36 48 60]
value is [0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333]
value is [0 0 0 0 0 0]
value is [    0     1    64   729  4096 15625]
value is [0 1 2 3 4 5]


In [164]:
a4=np.arange(4)
a5=np.arange(6)

In [165]:
a4

array([0, 1, 2, 3])

In [166]:
a5

array([0, 1, 2, 3])

In [167]:
a6=np.add(a4,a5)

In [168]:
a6

array([0, 2, 4, 6])

In [170]:
a6=np.subtract(a4,a5)

In [171]:
a6

array([0, 0, 0, 0])

In [176]:
a7=np.average(a4)

In [178]:
a7

1.5

In [181]:
a7=np.multiply(a4,a5)

In [182]:
a7

array([0, 1, 4, 9])

In [183]:
a8=np.multiply(a4,a5)

In [184]:
a8

array([0, 1, 4, 9])

## Tringonometric Function

- sin thetha
- cos theta
- tan theta


In [185]:
#not more than value 1

In [190]:
tri=np.linspace(0,np.pi,3)#most useful function in datascience


In [191]:
tri

array([0.        , 1.57079633, 3.14159265])

In [195]:
tri1=np.arange(1,np.pi,4)

In [196]:
angle=np.linspace(0,np.pi,3)#most useful function in datascience


In [197]:
angle

array([0.        , 1.57079633, 3.14159265])

In [200]:
?np.sin

In [201]:
np.sin(angle)

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [202]:
np.tan(angle)

array([ 0.00000000e+00,  1.63312394e+16, -1.22464680e-16])

In [203]:
np.cos(angle)

array([ 1.000000e+00,  6.123234e-17, -1.000000e+00])

In [7]:
value_of_output=[-1,0,1]

In [8]:
import numpy as np

In [9]:
np.arcsin(value_of_output)


array([-1.57079633,  0.        ,  1.57079633])

In [10]:
np.arcsin(value_of_output)

array([-1.57079633,  0.        ,  1.57079633])

In [11]:
import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6]])

print(f'Original Array:\n{arr1}')

arr1_transpose = arr1.transpose()

print(f'Transposed Array:\n{arr1_transpose}')

Original Array:
[[1 2 3]
 [4 5 6]]
Transposed Array:
[[1 4]
 [2 5]
 [3 6]]


In [16]:
arr=np.arange(3,3)

In [17]:
print(arr)

[]


In [22]:
a4=np.arange(1,10)


In [24]:
a4

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr=a4.reshape(3,3)

In [29]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
arr.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [31]:
?np.sin


In [32]:
np.sin(np.pi/4)

0.7071067811865476

In [35]:
val=(2**0.2)

In [37]:
1/val

0.8705505632961241

In [39]:
np.pi

3.141592653589793

In [42]:
angle =np.linspace(0,np.pi,6)

In [43]:
angle

array([0.        , 0.62831853, 1.25663706, 1.88495559, 2.51327412,
       3.14159265])

In [52]:
np.tan(angle)

array([ 0.00000000e+00,  7.26542528e-01,  3.07768354e+00, -3.07768354e+00,
       -7.26542528e-01, -1.22464680e-16])

In [49]:
np.cos(0)

1.0

In [50]:
np.log(100)

4.605170185988092

In [53]:
np.tan(90)

-1.995200412208242

In [54]:
vales_of_output=[-1,0,1]

In [56]:
print("Sin",np.arcsin(value_of_output))
print("Cos",np.arccos(value_of_output))
print("tan",np.arctan(value_of_output))

Sin [-1.57079633  0.          1.57079633]
Cos [3.14159265 1.57079633 0.        ]
tan [-0.78539816  0.          0.78539816]


In [59]:
val=np.sin(0)

ZeroDivisionError: division by zero

In [63]:
np.log10(1000)

3.0

In [65]:
?np.log

In [69]:
np.log10(10**8)

8.0

In [70]:
np.log10(100)

2.0

In [72]:
log=[1,2,3]

In [78]:
np.exp2(log)

array([2., 4., 8.])

In [79]:
?np.exp

In [89]:
log2=[1,2,4,6,8,10]

In [92]:
np.log2(log2)

array([0.        , 1.        , 2.        , 2.5849625 , 3.        ,
       3.32192809])

In [91]:
np.log10(log2)

array([0.        , 0.30103   , 0.60205999, 0.77815125, 0.90308999,
       1.        ])

In [93]:
log3=[0,0.002,0.0045,0.1]

In [94]:
log3

[0, 0.002, 0.0045, 0.1]

In [96]:
np.expm1(log3) # here 1 is callled of -1

array([0.        , 0.002002  , 0.00451014, 0.10517092])

In [99]:
np.log1p(log3)#log(1+x)

array([0.        , 0.001998  , 0.00448991, 0.09531018])

In [100]:
tri=np.array([np.pi/2])

In [101]:
tri

array([1.57079633])

In [102]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',

In [103]:
np.sinh(10)

11013.232874703393

In [105]:
##aggregate function
ag=np.random.randint(10,size=(3,4))

In [106]:
ag

array([[3, 5, 9, 4],
       [7, 1, 7, 2],
       [5, 5, 5, 8]])

In [107]:
ag.sum()

61

In [108]:
ag.max()

9

In [109]:
ag.min()

1

In [110]:
ag.std()

2.2897719440056807

In [111]:
ag.mean()#standered devision

5.083333333333333

In [113]:
median(ag)

NameError: name 'median' is not defined

In [115]:
np.median(ag)

5.0

In [118]:
np.any(ag)

True

In [119]:
np.var(ag)

5.2430555555555545

## Numpy All function
- np.min(*arg)
- np.max(*arg)
- np.sum(*arg) **
- np.std(*arg)**
- np.var(*arg)**
- np.median(*arg)
- np.all(*arg)
- np.min(*arg)
- np.mean(*arg)**
- np.Any(*arg)