In [1]:
import numpy as np  
arr = np.array([0, 30, 60, 90])  
print("printing the sin values of different angles")  
  
sinval = np.sin(arr*np.pi/180)  
  
print(sinval)  
print("printing the inverse of the sin")  
cosec = np.arcsin(sinval)  
  
print(cosec)  
  
print("printing the values in degrees")  
print(np.degrees(cosec))  
  
print("\nprinting the cos values of different angles")  
cosval = np.cos(arr*np.pi/180)  
  
print(cosval)  
print("printing the inverse of the cos")  
sec = np.arccos(cosval)  
print(sec)  
  
print("\nprinting the values in degrees")  
print(np.degrees(sec))  
  
print("\nprinting the tan values of different angles")  
tanval = np.tan(arr*np.pi/180)  
  
print(tanval)  
print("printing the inverse of the tan")  
cot = np.arctan(tanval)  
print(cot)  
  
print("\nprinting the values in degrees")  
print(np.degrees(cot))  

printing the sin values of different angles
[0.        0.5       0.8660254 1.       ]
printing the inverse of the sin
[0.         0.52359878 1.04719755 1.57079633]
printing the values in degrees
[ 0. 30. 60. 90.]

printing the cos values of different angles
[1.00000000e+00 8.66025404e-01 5.00000000e-01 6.12323400e-17]
printing the inverse of the cos
[0.         0.52359878 1.04719755 1.57079633]

printing the values in degrees
[ 0. 30. 60. 90.]

printing the tan values of different angles
[0.00000000e+00 5.77350269e-01 1.73205081e+00 1.63312394e+16]
printing the inverse of the tan
[0.         0.52359878 1.04719755 1.57079633]

printing the values in degrees
[ 0. 30. 60. 90.]
